#ifndef _DEFINITIONS_BLUE_H
#define _DEFINITIONS_BLUE_H

/*BLUE ROBOT PID START*/
const double FORWARD_KP = 0.8;
const double FORWARD_KI = 0;
const double FORWARD_KD = 0.2;

const double FORWARD_KPR = 0.6;
const double FORWARD_KIR = 0;
const double FORWARD_KDR = 0.21;

const double TURN_KP = 0.4;
const double TURN_KI = 0.0015;
const double TURN_KD = 0.01;
/*BLUE ROBOT PID END*/

/*BLUE ROBOT PORTS START*/
#define LEFT_MOTOR_FRONT_PORT 12
#define LEFT_MOTOR_REAR_PORT 20

#define RIGHT_MOTOR_FRONT_PORT 3
#define RIGHT_MOTOR_REAR_PORT 10

#define TOP_ROLLER_MOTOR_PORT 13
#define BOTTOM_ROLLER_MOTOR_PORT 4

#define SORTING_MOTOR_PORT 8
#define OPTICAL_PORT 7
#define OPTICAL_PORT_UPDATE 40
#define IMU_SENSOR_PORT 14

#define EVAC_MOTOR_PORT 16
/*BLUE ROBOT PORTS END*/

/*MATHS*/
#define Math_PI 3.1415
const int TICKS_PER_REVOLUTION = 360;
const double WHEEL_DIAMETER_CM = 10.5;
const double WHEEL_CIRCUMFERENCE_CM = WHEEL_DIAMETER_CM * Math_PI;
const double CM_PER_TICK = WHEEL_CIRCUMFERENCE_CM / TICKS_PER_REVOLUTION;

#endif